name: "Sample Workflow"
on: 
    push: 
        branches: 
        - main
jobs: 
    testing_job:
        runs-on: ubuntu-latest
        steps: 
            - name: "Welcome Step"
              run: |
                echo "Welcome to this step"