name: "Sample Workflow"

on: 
  push: 
    branches: 
      - main
  pull_request:

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Push Confirmation"
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "push successful"

      - name: "Pull Notification"
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "Pull successful"
